# MinIO S3 Data Explorer - Gold Layer

In [ ]:
# Cài đặt các thư viện cần thiết
import subprocess
import sys

# Tất cả packages cần thiết cho notebook
packages = [
    'minio',
    'pandas',
    'pyarrow',
    'confluent-kafka',
    'fastavro',
    'cachetools',
    'httpx',
    'attrs',
    'authlib',
    'requests'
]

print("[INFO] Cài đặt thư viện...\n")
failed_packages = []

for package in packages:
    try:
        # Thử import package (handle package name khác import name)
        if package == 'confluent-kafka':
            __import__('confluent_kafka')
        elif package == 'pyarrow':
            __import__('pyarrow')
        elif package == 'httpx':
            __import__('httpx')
        elif package == 'cachetools':
            __import__('cachetools')
        else:
            __import__(package)
        print(f"[OK] {package:<25} - đã có sẵn")
    except ImportError:
        print(f"[INSTALL] Đang cài {package:<25}...")
        try:
            subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", package])
            print(f"[OK] {package:<25} - cài xong")
        except Exception as err:
            print(f"[ERROR] {package:<25} - LỖI: {err}")
            failed_packages.append(package)

if failed_packages:
    print(f"\n[WARN] Các package cài đặt thất bại: {failed_packages}")
else:
    print("\n[OK] Tất cả thư viện sẵn sàng!")

[INFO] Cài đặt thư viện...

[OK] minio                     - đã có sẵn
[OK] pandas                    - đã có sẵn
[OK] pyarrow                   - đã có sẵn
[OK] confluent-kafka           - đã có sẵn
[OK] fastavro                  - đã có sẵn
[OK] cachetools                - đã có sẵn
[OK] httpx                     - đã có sẵn
[OK] attrs                     - đã có sẵn
[OK] authlib                   - đã có sẵn
[OK] requests                  - đã có sẵn

[OK] Tất cả thư viện sẵn sàng!

In [1]:
import os
import io
from minio import Minio
import pandas as pd
import pyarrow.parquet as pq
from datetime import datetime

print("[INFO] Imports hoàn tất!")

[INFO] Imports hoàn tất!

## MinIO Configuration for Gold Layer Exploration

In [3]:
MINIO_CONFIG = {
    'endpoint': 'localhost:9000',
    'access_key': 'minioadmin',
    'secret_key': 'minioadmin',
    'secure': False,
    'region': 'ap-southeast-1'
}

BUCKET_NAME = 'data-lake'
GOLD_PATH_PREFIX = 'warehouse/gold/'

try:
    minio_client = Minio(
        MINIO_CONFIG['endpoint'],
        access_key=MINIO_CONFIG['access_key'],
        secret_key=MINIO_CONFIG['secret_key'],
        secure=MINIO_CONFIG['secure'],
        region=MINIO_CONFIG['region']
    )
    
    # Kiểm tra kết nối
    if minio_client.bucket_exists(BUCKET_NAME):
        print(f"[SUCCESS] Kết nối MinIO thành công! Bucket '{BUCKET_NAME}' đã sẵn sàng.")
    else:
        print(f"[ERROR] Bucket '{BUCKET_NAME}' không tồn tại.")
    
except Exception as e:
    print(f"[ERROR] Kết nối MinIO thất bại: {e}")

[SUCCESS] Kết nối MinIO thành công! Bucket 'data-lake' đã sẵn sàng.

## 📊 Overview of the tables in the Gold layer

There are two main mart tables in the Gold layer:
1. **mart_sales_overview**: sales details table (denormalized).
2. **mart_customer_lifetime_value**: customer behavior table.

In [4]:
def list_gold_tables():
    try:
        objects = minio_client.list_objects(BUCKET_NAME, prefix=GOLD_PATH_PREFIX, recursive=True)
        tables = {}
        for obj in objects:
            parts = obj.object_name.split('/')
            if len(parts) >= 3:
                table_name = parts[2]
                if table_name not in tables:
                    tables[table_name] = {'count': 0, 'size_mb': 0}
                tables[table_name]['count'] += 1
                tables[table_name]['size_mb'] += obj.size / (1024 * 1024)
        return tables
    except Exception as e:
        print(f"Lỗi: {e}")
        return {}

gold_tables = list_gold_tables()
print("\nBảng Gold hiện có trong MinIO:")
print("=" * 50)
for name, info in gold_tables.items():
    print(f"- {name:<30} | {info['count']:>3} objects | {info['size_mb']:>6.2f} MB")

Bảng Gold hiện có trong MinIO:
==================================================
- mart_customer_lifetime_value   |   6 objects |   0.02 MB
- mart_sales_overview            |   6 objects |   0.72 MB

## Explore the detailed data.

In [5]:
def read_table_sample(table_name, limit=50):
    prefix = f"{GOLD_PATH_PREFIX}{table_name}/data/"
    try:
        objects = list(minio_client.list_objects(BUCKET_NAME, prefix=prefix, recursive=True))
        parquet_files = [obj.object_name for obj in objects if obj.object_name.endswith('.parquet')]
        
        if not parquet_files:
            print(f"[WARN] Không tìm thấy file dữ liệu cho bảng {table_name}")
            return
        
        # Đọc file đầu tiên
        response = minio_client.get_object(BUCKET_NAME, parquet_files[0])
        df = pd.read_parquet(io.BytesIO(response.read()))
        
        print(f"\n{'='*80}")
        print(f"📊 TABLE: {table_name.upper()}")
        print(f"{'='*80}")
        print(f"\n[SCHEMA]:")
        print(df.dtypes)
        print(f"\n[SAMPLE - Top {limit} rows]:")
        display(df.head(limit))
        
    except Exception as e:
        print(f"[ERROR] Lỗi khi đọc bảng {table_name}: {e}")

for table in gold_tables.keys():
    read_table_sample(table)

================================================================================
📊 TABLE: MART_CUSTOMER_LIFETIME_VALUE
================================================================================

[SCHEMA]:
customer_id            str
total_orders         int64
total_spent_usd    float64
first_order         object
last_order          object
dtype: object

[SAMPLE - Top 50 rows]:

     customer_id  total_orders  total_spent_usd first_order  last_order
0   usr_uxaudm7j            97      289943.0301  2026-04-14  2026-04-14
1   usr_916np9zk           100      261205.4079  2026-04-14  2026-04-14
2   usr_9o3gv6qz           108      289899.1417  2026-04-14  2026-04-14
3   usr_jfxlh21w           126      378131.2240  2026-04-14  2026-04-14
4   usr_usza29fq           111      354135.6134  2026-04-14  2026-04-14
5   usr_gry37jk4           112      345672.9106  2026-04-14  2026-04-14
6   usr_r4hi0lq2           106      300023.4218  2026-04-14  2026-04-14
7   usr_lly5d8ph           105      290292.0303  2026-04-14  2026-04-14
8   usr_d3tt24eo            97      296120.7970  2026-04-14  2026-04-14
9   usr_mw29mayx            99      325742.6989  2026-04-14  2026-04-14
10  usr_sxaamm2s           107      344852.5112  2026-04-14  2026-04-14
11  usr_ldolqxe0           115      359213.5820  2026-04-14  2026-04-14
12  usr_shcltibi            96      287949.9032  2026-04-14  2026-04-14
13  usr_9mwjfjrl           124      361993.9706  2026-04-14  2026-04-14
14  usr_fijc3yj7           113      363703.5375  2026-04-14  2026-04-14
15  usr_4rx84gh1           113      350402.2243  2026-04-14  2026-04-14
16  usr_nbinn6jv           105      310606.2647  2026-04-14  2026-04-14
17  usr_4gc2g03t           103      344448.8898  2026-04-14  2026-04-14
18  usr_3egg5mrm            99      312840.9150  2026-04-14  2026-04-14
19  usr_6ojol16c           114      320245.7308  2026-04-14  2026-04-14
20  usr_62kkat9q           128      414154.2400  2026-04-14  2026-04-14
21  usr_u3vt401r           108      294325.8577  2026-04-14  2026-04-14
22  usr_dvkuspht           119      393270.9519  2026-04-14  2026-04-14
23  usr_tzdw2opy            92      249671.8567  2026-04-14  2026-04-14
24  usr_0z5wmka4           108      354509.4598  2026-04-14  2026-04-14
25  usr_rv879xwb            90      242543.5793  2026-04-14  2026-04-14
26  usr_5j3xaqxe           108      340080.8596  2026-04-14  2026-04-14
27  usr_1pfkc3kp            96      267922.1542  2026-04-14  2026-04-14
28  usr_g7ayph4d            99      288793.5378  2026-04-14  2026-04-14
29  usr_nnx24a8j            90      274632.8057  2026-04-14  2026-04-14
30  usr_la81mgq8           134      440140.2455  2026-04-14  2026-04-14
31  usr_0pl5str9           120      377382.9952  2026-04-14  2026-04-14
32  usr_jtdb50hv           118      289927.6314  2026-04-14  2026-04-14
33  usr_ggrzaq08           106      314395.6630  2026-04-14  2026-04-14
34  usr_ikr3xixr           101      312364.3524  2026-04-14  2026-04-14
35  usr_2q66q4d7           100      309060.3920  2026-04-14  2026-04-14
36  usr_f5mwokm2           119      383835.5878  2026-04-14  2026-04-14
37  usr_2fws5qg0           118      306601.4466  2026-04-14  2026-04-14
38  usr_sb9yk9fu           105      332335.9439  2026-04-14  2026-04-14
39  usr_9qh554bt            99      314725.0147  2026-04-14  2026-04-14
40  usr_a8x8hnm5            85      235500.5392  2026-04-14  2026-04-14
41  usr_pi3m51j5            98      265554.4928  2026-04-14  2026-04-14
42  usr_c2zuy3a8           126      356784.5852  2026-04-14  2026-04-14
43  usr_ndk84jun           102      357066.3571  2026-04-14  2026-04-14
44  usr_ltno53qn           107      333521.4845  2026-04-14  2026-04-14
45  usr_i949j9cm            78      252869.7777  2026-04-14  2026-04-14
46  usr_bb6ms1kn            91      271582.6652  2026-04-14  2026-04-14
47  usr_p6k9qu8n           115      325432.5730  2026-04-14  2026-04-14
48  usr_os169x6k           124      343976.9463  2026-04-14  2026-04-14
49  usr_hjnet2rt           116      368356.5480  2026-04-14  2026-04-14

================================================================================
📊 TABLE: MART_SALES_OVERVIEW
================================================================================

[SCHEMA]:
order_id              str
order_date         object
customer_id           str
country               str
product_name          str
category              str
quantity            int32
amount_usd        float64
payment_status        str
dtype: object

[SAMPLE - Top 50 rows]:

,order_id,order_date,customer_id,country,product_name,category,quantity,amount_usd,payment_status
0,ord_0007ebbzuh,2026-04-14,usr_9vmvopd0,TH,Product 98,Home,1,141.5916,SETTLED
1,ord_001qx6qdna,2026-04-14,usr_8g0sa7ue,LA,Product 147,Sports,1,15.8952,SETTLED
2,ord_009rw5d76g,2026-04-14,usr_8higrhr7,MM,Product 133,Electronics,19,1528.0256,SETTLED
3,ord_009w5j03om,2026-04-14,usr_xo72480b,SG,Product 64,Electronics,1,278.8764,PENDING
4,ord_00d47ifn5v,2026-04-14,usr_tf1w0oem,KH,Product 148,Electronics,2,597.2224,SETTLED
5,ord_00enprn1nh,2026-04-14,usr_rqikzr01,VN,Product 10,Beauty,8,2285.2000,PENDING
6,ord_00ey2wzbnw,2026-04-14,usr_06ud4yqs,TH,Product 133,Electronics,2,160.8448,SETTLED
7,ord_00fga3l9jt,2026-04-14,usr_zkj1lkj8,ID,Product 124,Electronics,7,846.3000,FAILED
8,ord_00hjf87f07,2026-04-14,usr_kzznwawv,KH,Product 192,Electronics,20,1764.6000,SETTLED
9,ord_00hr2nq9t0,2026-04-14,usr_8c0or0ad,ID,Product 70,Beauty,5,1561.4000,FAILED
10,ord_00ii66agh6,2026-04-14,usr_0tzzs3yw,SG,Product 137,Books,10,3924.0000,PENDING
11,ord_00jjvfqm8u,2026-04-14,usr_lly5d8ph,MM,Product 19,Beauty,9,1140.2100,SETTLED
12,ord_00monusv9n,2026-04-14,usr_6pzzopkc,PH,Product 93,Books,13,473.1597,SETTLED
13,ord_00nobpyt4s,2026-04-14,usr_4gc2g03t,TH,Product 193,Home,12,2992.0800,SETTLED
14,ord_00qgrstb6v,2026-04-14,usr_5gztlcef,MY,Product 124,Electronics,13,1571.7000,SETTLED
15,ord_00qzojlxpn,2026-04-14,usr_s9rvw1um,TH,Product 52,Home,18,6039.2448,Unknown
16,ord_00r270yorb,2026-04-14,usr_la81mgq8,PH,Product 131,Books,19,5972.5056,SETTLED
17,ord_00raww2rwc,2026-04-14,usr_vrge8btb,MM,Product 87,Electronics,16,2135.1072,SETTLED
18,ord_00sfmxkgfu,2026-04-14,usr_uxaudm7j,TH,Product 162,Home,13,4194.9700,SETTLED
19,ord_00wutu1jl4,2026-04-14,usr_sz619s62,ID,Product 28,Sports,8,3838.9760,SETTLED
20,ord_00ybje845b,2026-04-14,usr_4s9jqinv,VN,Product 194,Home,12,2589.9408,Unknown
21,ord_00yeue57rp,2026-04-14,usr_k3keilx4,KH,Product 50,Books,20,4056.8320,SETTLED
22,ord_012yas2efc,2026-04-14,usr_n3rx3ehq,LA,Product 171,Sports,3,846.6000,SETTLED
23,ord_014l09vqw6,2026-04-14,usr_4gc2g03t,TH,Product 85,Electronics,14,1635.0600,SETTLED
24,ord_016i4joxw6,2026-04-14,usr_li4n8t72,SG,Product 99,Fashion,14,3329.6200,Unknown
25,ord_016ujhzmwf,2026-04-14,usr_e6bjtr2r,PH,Product 154,Beauty,7,102.2700,PENDING
26,ord_017bg48nmd,2026-04-14,usr_isiwb2ez,ID,Product 23,Home,14,223.1600,Unknown
27,ord_01a1dkk0rb,2026-04-14,usr_hn7ic6vk,SG,Product 66,Beauty,18,372.0276,Unknown
28,ord_01bn2nilr3,2026-04-14,usr_vitu2feh,LA,Product 184,Electronics,8,486.0928,Unknown
29,ord_01ckvcurg1,2026-04-14,usr_wyml8ney,MM,Product 96,Fashion,8,2369.7408,SETTLED
30,ord_01dnp6dv8i,2026-04-14,usr_1ske38wd,ID,Product 147,Sports,16,254.3232,SETTLED
31,ord_01erxbx3j8,2026-04-14,usr_5fipmt5z,SG,Product 53,Home,1,296.6900,SETTLED
32,ord_01fqbkq9tc,2026-04-14,usr_4gc2g03t,TH,Product 187,Beauty,11,4844.2900,Unknown
33,ord_01hzo6f4tn,2026-04-14,usr_3egg5mrm,PH,Product 186,Electronics,13,6235.8400,SETTLED
34,ord_01iwo10cjs,2026-04-14,usr_p9mvvlfa,LA,Product 180,Electronics,16,5250.8800,Unknown
35,ord_01j3qfo0k5,2026-04-14,usr_1vsk1shu,KH,Product 51,Sports,18,1690.5600,SETTLED
36,ord_01jeutt9o5,2026-04-14,usr_37wee5bw,MY,Product 41,Beauty,17,5818.2500,SETTLED
37,ord_01jt8v9tkt,2026-04-14,usr_5jcae3tx,SG,Product 145,Fashion,14,4076.7636,SETTLED
38,ord_01m1jno2vi,2026-04-14,usr_4owm7i5k,BN,Product 123,Beauty,3,986.3700,SETTLED
39,ord_01na8g1fd1,2026-04-14,usr_2w40wbnt,TH,Product 165,Fashion,1,264.8960,SETTLED
40,ord_01phma4gj0,2026-04-14,usr_46vhksn0,LA,Product 171,Sports,8,2505.9360,PENDING
41,ord_01qescuf3b,2026-04-14,usr_67nxfvjb,VN,Product 176,Home,9,1871.0784,SETTLED
42,ord_01s1rsn0ny,2026-04-14,usr_d2vk3jy0,SG,Product 141,Electronics,5,928.1265,SETTLED
43,ord_01sq08ntgg,2026-04-14,usr_xd04cgmn,SG,Product 45,Home,11,6727.9872,SETTLED
44,ord_01u62hawkm,2026-04-14,usr_wy4fvjvg,TH,Product 199,Home,14,2882.2038,PENDING
45,ord_01v1k4vp7s,2026-04-14,usr_916np9zk,ID,Product 53,Home,5,1483.4500,Unknown
46,ord_01wa03wpd1,2026-04-14,usr_mw29mayx,ID,Product 161,Fashion,20,8664.8320,PENDING
47,ord_01wlgti2k1,2026-04-14,usr_6iqrl29l,ID,Product 190,Books,15,2808.5760,Unknown
48,ord_01zi4w5cp6,2026-04-14,usr_emf881f3,KH,Product 66,Beauty,9,186.0138,SETTLED
49,ord_0204fd93n8,2026-04-14,usr_37wee5bw,LA,Product 174,Books,8,856.9856,SETTLED

In [6]:
# Check for duplicates in mart_customer_lifetime_value
import io

print("="*80)
print("DUPLICATE CHECK: mart_customer_lifetime_value")
print("="*80)

try:
    # Read all parquet files from mart_customer_lifetime_value
    prefix = f"{GOLD_PATH_PREFIX}mart_customer_lifetime_value/data/"
    objects = list(minio_client.list_objects(BUCKET_NAME, prefix=prefix, recursive=True))
    parquet_files = [obj.object_name for obj in objects if obj.object_name.endswith('.parquet')]
    
    if not parquet_files:
        print(f"❌ No parquet files found for mart_customer_lifetime_value")
    else:
        print(f"\n✓ Found {len(parquet_files)} parquet files")
        
        # Read all files and combine
        dfs = []
        for pq_file in parquet_files:
            response = minio_client.get_object(BUCKET_NAME, pq_file)
            df_part = pd.read_parquet(io.BytesIO(response.read()))
            dfs.append(df_part)
        
        df_clv = pd.concat(dfs, ignore_index=True)
        
        total_records = len(df_clv)
        unique_customers = df_clv['customer_id'].nunique()
        
        print(f"\nTotal records: {total_records}")
        print(f"Unique customers: {unique_customers}")
        
        if total_records == unique_customers:
            print("\n✅ NO DUPLICATES - Each customer appears exactly once")
        else:
            print(f"\n⚠️  DUPLICATES FOUND - Extra records: {total_records - unique_customers}")
            
            # Show duplicate customers
            dup_counts = df_clv['customer_id'].value_counts()
            dupes = dup_counts[dup_counts > 1]
            
            print(f"\nCustomers with duplicates: {len(dupes)}")
            if len(dupes) > 0:
                print("\nTop 10 duplicated customers:")
                print(dupes.head(10))
        
        print("\nSample records from mart_customer_lifetime_value:")
        display(df_clv.head(10))
        
except Exception as e:
    print(f"❌ Error: {e}")

================================================================================
DUPLICATE CHECK: mart_customer_lifetime_value
================================================================================

✓ Found 1 parquet files

Total records: 500
Unique customers: 500

✅ NO DUPLICATES - Each customer appears exactly once

Sample records from mart_customer_lifetime_value:

    customer_id  total_orders  total_spent_usd first_order  last_order
0  usr_uxaudm7j            97      289943.0301  2026-04-14  2026-04-14
1  usr_916np9zk           100      261205.4079  2026-04-14  2026-04-14
2  usr_9o3gv6qz           108      289899.1417  2026-04-14  2026-04-14
3  usr_jfxlh21w           126      378131.2240  2026-04-14  2026-04-14
4  usr_usza29fq           111      354135.6134  2026-04-14  2026-04-14
5  usr_gry37jk4           112      345672.9106  2026-04-14  2026-04-14
6  usr_r4hi0lq2           106      300023.4218  2026-04-14  2026-04-14
7  usr_lly5d8ph           105      290292.0303  2026-04-14  2026-04-14
8  usr_d3tt24eo            97      296120.7970  2026-04-14  2026-04-14
9  usr_mw29mayx            99      325742.6989  2026-04-14  2026-04-14

In [7]:
# Check for duplicates in mart_sales_overview
import io

print("="*80)
print("DUPLICATE CHECK: mart_sales_overview")
print("="*80)

try:
    # Read all parquet files from mart_sales_overview
    prefix = f"{GOLD_PATH_PREFIX}mart_sales_overview/data/"
    objects = list(minio_client.list_objects(BUCKET_NAME, prefix=prefix, recursive=True))
    parquet_files = [obj.object_name for obj in objects if obj.object_name.endswith('.parquet')]
    
    if not parquet_files:
        print(f"❌ No parquet files found for mart_sales_overview")
    else:
        print(f"\n✓ Found {len(parquet_files)} parquet files")
        
        # Read all files and combine
        dfs = []
        for pq_file in parquet_files:
            response = minio_client.get_object(BUCKET_NAME, pq_file)
            df_part = pd.read_parquet(io.BytesIO(response.read()))
            dfs.append(df_part)
        
        df_sales = pd.concat(dfs, ignore_index=True)
        
        total_records = len(df_sales)
        unique_orders = df_sales['order_id'].nunique()
        
        print(f"\nTotal records: {total_records}")
        print(f"Unique orders: {unique_orders}")
        
        if total_records == unique_orders:
            print("\n✅ NO DUPLICATES - Each order appears exactly once")
        else:
            print(f"\n⚠️  DUPLICATES FOUND - Extra records: {total_records - unique_orders}")
            
            # Show duplicate orders
            dup_counts = df_sales['order_id'].value_counts()
            dupes = dup_counts[dup_counts > 1]
            
            print(f"\nOrders with duplicates: {len(dupes)}")
            if len(dupes) > 0:
                print("\nTop 10 duplicated orders:")
                print(dupes.head(10))
        
        print("\nSample records from mart_sales_overview:")
        display(df_sales.head(10))
        
except Exception as e:
    print(f"❌ Error: {e}")

================================================================================
DUPLICATE CHECK: mart_sales_overview
================================================================================

✓ Found 1 parquet files

Total records: 52966
Unique orders: 52966

✅ NO DUPLICATES - Each order appears exactly once

Sample records from mart_sales_overview:

,order_id,order_date,customer_id,country,product_name,category,quantity,amount_usd,payment_status
0,ord_0007ebbzuh,2026-04-14,usr_9vmvopd0,TH,Product 98,Home,1,141.5916,SETTLED
1,ord_001qx6qdna,2026-04-14,usr_8g0sa7ue,LA,Product 147,Sports,1,15.8952,SETTLED
2,ord_009rw5d76g,2026-04-14,usr_8higrhr7,MM,Product 133,Electronics,19,1528.0256,SETTLED
3,ord_009w5j03om,2026-04-14,usr_xo72480b,SG,Product 64,Electronics,1,278.8764,PENDING
4,ord_00d47ifn5v,2026-04-14,usr_tf1w0oem,KH,Product 148,Electronics,2,597.2224,SETTLED
5,ord_00enprn1nh,2026-04-14,usr_rqikzr01,VN,Product 10,Beauty,8,2285.2000,PENDING
6,ord_00ey2wzbnw,2026-04-14,usr_06ud4yqs,TH,Product 133,Electronics,2,160.8448,SETTLED
7,ord_00fga3l9jt,2026-04-14,usr_zkj1lkj8,ID,Product 124,Electronics,7,846.3000,FAILED
8,ord_00hjf87f07,2026-04-14,usr_kzznwawv,KH,Product 192,Electronics,20,1764.6000,SETTLED
9,ord_00hr2nq9t0,2026-04-14,usr_8c0or0ad,ID,Product 70,Beauty,5,1561.4000,FAILED

In [17]:
# Check for NULL values in Gold tables
import io

print("=" * 80)
print("NULL CHECK: mart_sales_overview")
print("=" * 80)

try:
    # Read all parquet files from mart_sales_overview
    prefix = f"{GOLD_PATH_PREFIX}mart_sales_overview/data/"
    objects = list(minio_client.list_objects(BUCKET_NAME, prefix=prefix, recursive=True))
    parquet_files = [obj.object_name for obj in objects if obj.object_name.endswith('.parquet')]
    
    if not parquet_files:
        print(f"❌ No parquet files found for mart_sales_overview")
    else:
        print(f"\n✓ Found {len(parquet_files)} parquet files")
        
        # Read all files and combine
        dfs = []
        for pq_file in parquet_files:
            response = minio_client.get_object(BUCKET_NAME, pq_file)
            df_part = pd.read_parquet(io.BytesIO(response.read()))
            dfs.append(df_part)
        
        df_sales = pd.concat(dfs, ignore_index=True)
        
        print(f"\nTotal rows: {len(df_sales)}")
        print(f"Columns: {list(df_sales.columns)}\n")
        
        # Check for NULL in each column
        columns_to_check = ["order_id", "order_date", "customer_id", "country", "product_name", "category", "quantity", "amount_usd", "payment_status"]
        
        print("NULL Count by Column:")
        print("-" * 40)
        has_nulls = False
        for col_name in columns_to_check:
            if col_name in df_sales.columns:
                null_count = df_sales[col_name].isna().sum()
                total = len(df_sales)
                pct = (null_count / total * 100) if total > 0 else 0
                print(f"{col_name:20} NULL: {null_count:6} ({pct:.1f}%)")
                if null_count > 0:
                    has_nulls = True
        
        if not has_nulls:
            print("\n✅ NO NULL VALUES - All columns have complete data!")
        else:
            # Show details for columns with NULLs
            print("\n" + "="*80)
            print("DETAILS FOR COLUMNS WITH NULL VALUES")
            print("="*80)
            
            for col_name in columns_to_check:
                if col_name in df_sales.columns and df_sales[col_name].isna().sum() > 0:
                    print(f"\n### {col_name} ###")
                    print(f"Sample rows with NULL {col_name}:")
                    null_rows = df_sales[df_sales[col_name].isna()].head(3)
                    print(null_rows[["order_id", col_name]].to_string())
        
except Exception as e:
    print(f"❌ Error: {e}")
    import traceback
    traceback.print_exc()

================================================================================
NULL CHECK: mart_sales_overview
================================================================================

✓ Found 1 parquet files

Total rows: 52966
Columns: ['order_id', 'order_date', 'customer_id', 'country', 'product_name', 'category', 'quantity', 'amount_usd', 'payment_status']

NULL Count by Column:
----------------------------------------
order_id             NULL:      0 (0.0%)
order_date           NULL:      0 (0.0%)
customer_id          NULL:      0 (0.0%)
country              NULL:      0 (0.0%)
product_name         NULL:      0 (0.0%)
category             NULL:      0 (0.0%)
quantity             NULL:      0 (0.0%)
amount_usd           NULL:      0 (0.0%)
payment_status       NULL:      0 (0.0%)

✅ NO NULL VALUES - All columns have complete data!